### ISSUE TITLE
[2단계] 본 api 추가

### ISSUE THREAD

**Issue by som-syom** [42openproject/whatdidyoueat#105]
차차 수정해야할 부분은 많은데 다 따로 이슈만들기 애매해서 여기다 리스트화 해놓겠습니다

- [x] 캘린더
- [x] 포스트
ProfilePage 팔로잉/팔로워 -> 이건 아직 구현안된거다보니 제외하겠습닌다
- [x] ProfilePage 태그
- [x] 캘린더 재 수정
- [x] 닉네임 변경 중복 체크

**Comment by som-syom** [comment]
생각해보니 닉네임 중복체크에
프론트/백 둘 다에서 영어만 가능하도록 예외처리 필요해보입니다
@42-mki

**Comment by 42-mki** [comment]
영어만 되게 추가하기!

**Comment by 42-mki** [comment]
@som-syom 영어만 되게 추가하기!
