### ISSUE TITLE
[0단계] UML 작성

### ISSUE THREAD

**Issue by som-syom** [42openproject/whatdidyoueat#12]
[WKPL-3]UML 작성

[WKPL-3]: https://ft-wopark.atlassian.net/browse/WKPL-3?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by 42-mki** [comment]
UML Wiki에 추가했습니다.
