### ISSUE TITLE
[0단계] 개발환경 세팅

### ISSUE THREAD

**Issue by som-syom** [42openproject/whatdidyoueat#13]
[WKPL-15] 개발환경 세팅

[WKPL-15]: https://ft-wopark.atlassian.net/browse/WKPL-15?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by 42-mki** [comment]
Wiki는 수정해야 합니다.
https://github.com/42openproject/whatdidyoueat/wiki/%EA%B0%9C%EB%B0%9C-%ED%99%98%EA%B2%BD
