### ISSUE TITLE
[0단계] 코딩컨벤션 정의

### ISSUE THREAD

**Issue by som-syom** [42openproject/whatdidyoueat#14]
[WKPL-10] 코딩컨벤션 정의

[WKPL-10]: https://ft-wopark.atlassian.net/browse/WKPL-10?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by 42-mki** [comment]
커밋 컨벤션 정리 링크입니다. 수정되었습니당
https://github.com/42openproject/whatdidyoueat/wiki/%EC%BD%94%EB%94%A9-%EC%BB%A8%EB%B2%A4%EC%85%98
