### ISSUE TITLE
[0단계] UI/UX 설계

### ISSUE THREAD

**Issue by som-syom** [42openproject/whatdidyoueat#16]
[WKPL-8] UI/UX 설계

[WKPL-8]: https://ft-wopark.atlassian.net/browse/WKPL-8?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by 42-mki** [comment]
링크가 달려있으면 Close하겠습니다.
https://xd.adobe.com/view/c1915f24-939c-4389-8eea-b24e6f6f472a-94c2/grid
