### ISSUE TITLE
[1단계] 닉네임 설정 페이지 구현

### ISSUE THREAD

**Issue by som-syom** [42openproject/whatdidyoueat#20]
[WKPL-23] 닉네임 설정 페이지 구현
임시로 localStorage 에 저장

[WKPL-23]: https://ft-wopark.atlassian.net/browse/WKPL-23?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by 42-mki** [comment]
acf59a47861694a5c5df5f07d56a02c27d68d72d
