### ISSUE TITLE
[1단계] express mysql 연동

### ISSUE THREAD

**Issue by som-syom** [42openproject/whatdidyoueat#22]
[WKPL-25] express mysql 연동

[WKPL-25]: https://ft-wopark.atlassian.net/browse/WKPL-25?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by 42-mki** [comment]
d449f45a30989f27178e21982ff78a9cc55c6abe
