### ISSUE TITLE
[1단계] ERD 를 mysql 로 옮기기

### ISSUE THREAD

**Issue by som-syom** [42openproject/whatdidyoueat#24]
[WKPL-24] ERD를 mysql 로 옮기기

[WKPL-24]: https://ft-wopark.atlassian.net/browse/WKPL-24?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by 42-mki** [comment]
API문서를 기반으로 Sequelize를 사용해서 모델을 만들겠습니다.
