### ISSUE TITLE
[1단계] swagger 를 이용하여 API 문서 작성 테스트

### ISSUE THREAD

**Issue by som-syom** [42openproject/whatdidyoueat#25]
[WKPL-27] swagger 를 이용하여 API 문서 작성 테스트

[WKPL-27]: https://ft-wopark.atlassian.net/browse/WKPL-27?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by 42-mki** [comment]
7dd87d67f10da7f95800920457fe8219e9f9961a
