### ISSUE TITLE
[1단계] 메인페이지 퍼블리싱

### ISSUE THREAD

**Issue by som-syom** [42openproject/whatdidyoueat#26]
[WKPL-28] 메인페이지 퍼블리싱

기본 틀만 구성 (달력, 팔로잉 부분 제외)

[WKPL-28]: https://ft-wopark.atlassian.net/browse/WKPL-28?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by 42-mki** [comment]
e4c852b256289b29112f5c6ee7a5144ce7d95789
