### ISSUE TITLE
[1단계] Post 저장한거 Main Page 에서 띄우기

### ISSUE THREAD

**Issue by som-syom** [42openproject/whatdidyoueat#27]
[WKPL-32] Post 저장한거 Main Page 에서 띄우기

[WKPL-32]: https://ft-wopark.atlassian.net/browse/WKPL-32?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by 42-mki** [comment]
e92e3bf8dd0698ff1e84f9350ac308a191211c2c
