### ISSUE TITLE
[1단계] Swagger 테스트해보기

### ISSUE THREAD

**Issue by som-syom** [42openproject/whatdidyoueat#28]
[WKPL-33] Swagger 작업하기

[WKPL-33]: https://ft-wopark.atlassian.net/browse/WKPL-33?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by 42-mki** [comment]
테스트를 해보았습니다.
