### ISSUE TITLE
[1단계] nickname 클라이언트에서 서버로 전송하기

### ISSUE THREAD

**Issue by som-syom** [42openproject/whatdidyoueat#29]
[WKPL-34] nickname 클라이언트에서 서버로 전송하기

[WKPL-34]: https://ft-wopark.atlassian.net/browse/WKPL-34?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by 42-mki** [comment]
d449f45a30989f27178e21982ff78a9cc55c6abe
