### ISSUE TITLE
[1단계] post 작성한거 server 로 보내기

### ISSUE THREAD

**Issue by som-syom** [42openproject/whatdidyoueat#30]
[WKPL-35] post 작성한거 server 로 보내기

임시로 googleId로 받아오도록 설정

[WKPL-35]: https://ft-wopark.atlassian.net/browse/WKPL-35?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by 42-mki** [comment]
67b9e48884e17d5a82b513cd85806ce40fa0e4d4
