### ISSUE TITLE
[1단계] sequelize 사용해서 database 연결하기

### ISSUE THREAD

**Issue by som-syom** [42openproject/whatdidyoueat#31]
[WKPL-36] sequelize 적용하기

[WKPL-36]: https://ft-wopark.atlassian.net/browse/WKPL-36?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by 42-mki** [comment]
c0af772c16195e7ec099804424bc0ca6d1702c36
