### ISSUE TITLE
[1단계] Swagger /user 만들기

### ISSUE THREAD

**Issue by som-syom** [42openproject/whatdidyoueat#32]
[WKPL-37] Swagger 적용하기

[WKPL-37]: https://ft-wopark.atlassian.net/browse/WKPL-37?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by 42-mki** [comment]
7d2adf71f5143adf29c5766bb2074ee4a389a91c
