### ISSUE TITLE
[1단계] nickname DB에 저장 후 main page 에서 불러오기

### ISSUE THREAD

**Issue by som-syom** [42openproject/whatdidyoueat#33]
[WKPL-38] nickname DB에 저장 후 main page 에서 불러오기

[WKPL-38]: https://ft-wopark.atlassian.net/browse/WKPL-38?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by 42-mki** [comment]
635fc020d5fc73b8ae9b63d0247fbf88b10a16d8
