### ISSUE TITLE
[1단계] post DB에 저장 후 Main Page 에서 불러오기

### ISSUE THREAD

**Issue by som-syom** [42openproject/whatdidyoueat#34]
[WKPL-39] post DB에 저장 후 Main Page 에서 불러오기

[WKPL-39]: https://ft-wopark.atlassian.net/browse/WKPL-39?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by 42-mki** [comment]
040ef4ec8e1532401c2e400200600dda33c389cb
