### ISSUE TITLE
[1단계] AWS EC2에 mysql 연결

### ISSUE THREAD

**Issue by som-syom** [42openproject/whatdidyoueat#35]
[WKPL-40] AWS EC2에 mysql 연결

[WKPL-40]: https://ft-wopark.atlassian.net/browse/WKPL-40?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by 42-mki** [comment]
잘 적용했습니다.
