### ISSUE TITLE
[1단계] 다른 유저의 post 불러오기

### ISSUE THREAD

**Issue by som-syom** [42openproject/whatdidyoueat#36]
[WKPL-41] 다른 유저의 post 불러오기

임시로 nickname 으로 불러오도록 요청 하였음

[WKPL-41]: https://ft-wopark.atlassian.net/browse/WKPL-41?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by 42-mki** [comment]
f39e8ab5a835ab2a0bdcc0ebd33a883ab1057b4e
