### ISSUE TITLE
API 필요한거 요청

### ISSUE THREAD

**Issue by som-syom** [42openproject/whatdidyoueat#41]
필요한거 체크박스로 요청~

- [x] 메인페이지 포스트 title get/post 필요합니당~

**Comment by som-syom** [comment]
[API 문서]
- [https://github.com/42openproject/whatdidyoueat/wiki/API-%EB%AC%B8%EC%84%9C](https://github.com/42openproject/whatdidyoueat/wiki/API-%EB%AC%B8%EC%84%9C)

**Comment by 42-mki** [comment]
title/:id get/post 추가했습니다.
