### ISSUE TITLE
AWS EC2 접속방법 문서화

### ISSUE THREAD

**Issue by 42-mki** [42openproject/whatdidyoueat#54]
여러분들이 쉽게 사용할 수 있게 잘 작성해 놓겠습니다.

**Comment by 42-mki** [comment]
https://github.com/42openproject/whatdidyoueat/wiki/%EB%B0%B1%EC%97%94%EB%93%9C-%EC%84%9C%EB%B2%84-%EC%A1%B0%EC%9E%91%EB%B2%95

**Comment by wopa7210** [comment]
멋져!
