### ISSUE TITLE
[2단계] API 기타 수정사항

### ISSUE THREAD

**Issue by som-syom** [42openproject/whatdidyoueat#68]
- [x] #75
- [x] #74
- [x] posts 에 jwt 를 id 로 변경
- [x] posts 날짜로 받는거 기능 추가 필요 ("yyyy-mm-dd",)
- [ ] 에러시 상태 코드
- [x] #77

**Comment by som-syom** [comment]
[ 예외처리 ]

- [ ] 유저 nickname 사이즈 체크
- [ ] 유저 post title 사이즈 체크
- [ ] email 양식 체크
- [ ] 양식 자료형 string, number 등... 체크 (현재는 배열, 빈배열, 등등 넣으면 서버 오류 생김)

**Comment by som-syom** [comment]
닉네임 변경할때 중복체크 기능 체크할 수 있는 api 가 필요할거 같습니다!!
첫 로그인후에 닉네임설정 페이지와 프로필 페이지에서 사용해야합니다
@42-mki

**Comment by som-syom** [comment]
체크리스트 추가했습니다

**Comment by 42-mki** [comment]
@som-syom 
중복체크 api만들겠습니다!

**Comment by som-syom** [comment]
api 문서의 프로필페이지에
유저 프로필사진 관련 명세, 태그관리 삭제 명세 올렸습니다.
태그관리는 프로필페이지에서 삭제버튼으로만 존재하는데 delete 로 요청해야할지, post 로 업데이트식으로 요청해야할지 잘 모르겠네용... 어떻게 하면 좋을지 이야기 나눠봐야할거같아요

**Comment by 42-mki** [comment]
프로필 태그는 생각을 좀 해볼게요 흐흐으으으음 어떻게 하지....

**Comment by 42-mki** [comment]
Wiki 3단계 1번째 회의에 정리했기 때문에 닫습니다.

https://github.com/42openproject/whatdidyoueat/wiki/3%EB%8B%A8%EA%B3%84-1%EB%B2%88%EC%A7%B8-%ED%9A%8C%EC%9D%98
