### ISSUE TITLE
[2단계] api 요청주소, 포맷 수정, 전반적인 코드 수정

### ISSUE THREAD

**Issue by som-syom** [42openproject/whatdidyoueat#85]
드디어 dev로 와서
기존 요청들 수정하고 test api 랑 비교할 수 있도록 버튼 추가하겠습니다

✔️ 체크리스트

**구글로그인**
- [x] api url 수정
- [x] success 체크

**닉네임페이지**
- [x] api url 수정
- [x] success 체크

**메인페이지 닉네임 가져오기**
- [x] api url 수정
- [x] success 체크

**메인페이지 포스트 가져오기**
- [x] api url 수정
- [x] success 체크

**메인페이지 포스트 타이틀 가져오기**
- [x] api url 수정
- [x] success 체크

**메인페이지 포스트 타이틀 수정**
- [x] api url 수정
- [x] success 체크

**포스트 업로드**
- [x] api url 수정
- [x] success 체크

**프로필페이지 유저 닉네임 가져오기**
- [x] api url 수정
- [x] success 체크

**Comment by som-syom** [comment]
대공사 진행중입니다...
UserPage 도 뜯어고쳐야할거 같습니다...

**Comment by 42-mki** [comment]
dhyeon의 노력의 흔적.............
