### ISSUE TITLE
[2단계] 타이틀 같은 날짜 추가가 아니라 업데이트로 변경하기

### ISSUE THREAD

**Issue by 42-mki** [42openproject/whatdidyoueat#87]
빠르게 해결하겠습니다.

**Comment by 42-mki** [comment]
타이틀 없을 때 어떻게 해야 하지...

**Comment by som-syom** [comment]
> 타이틀 없을 때 어떻게 해야 하지...

시작날짜를 따로 저장해서 달력에서 선택못하게 하는게 맞을까요??
지금 캘린더에서 시작날짜 설정하면 그이전날짜는 선택못하게 할 수는 있습니다...!

**Comment by 42-mki** [comment]
수정했습니다.
