### ISSUE TITLE
[2단계] 새로고침시 요청에 [GET /%3Canonymous%3E] 404 오류 발생

### ISSUE THREAD

**Issue by som-syom** [42openproject/whatdidyoueat#89]
어디서 발생하는건지 모르겠고
이 요청이 언제 발생하는지 모르겠으나 확인이 필요할듯하여 기록합니다
찾아봐도 정보가 잘 나오지않네요 ㅜㅜ

**Comment by som-syom** [comment]
![image](https://user-images.githubusercontent.com/60869490/144958880-ff65ff32-bff3-41d5-9606-80408a5d831f.png)
왜 뜨는걸까요...

**Comment by 42-mki** [comment]
알수없는 신비한 녀석... 새로고침하니 해결되는 마법

**Comment by som-syom** [comment]
json-server 사용할때 생기는 문제 같습니다.....................
끄니까 안뜹니다
