### ISSUE TITLE
[0단계] 기획서 작성

### ISSUE THREAD

**Issue by som-syom** [42openproject/whatdidyoueat#9]
[WKPL-2]기획서 작성

[WKPL-2]: https://ft-wopark.atlassian.net/browse/WKPL-2?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by 42-mki** [comment]
기획서 Wiki에 작성했습니다.

**Comment by som-syom** [comment]
링크를 같이 남기면 좋을거같습니다

> 기획서 Wiki에 작성했습니다.
