### ISSUE TITLE
[2단계] 중복된 get nickname api 요청 줄이기

### ISSUE THREAD

**Issue by som-syom** [42openproject/whatdidyoueat#91]
현재 nickname 을 상태로 관리하고 있어서
컴포넌트간 이동이 뜻대로 안되어서 nickname get 요청을 여러번 날리는 상태인데
이부분에 대한 수정이 필요해 보입니다..
1-상태로 관리를 하지 않거나,
2-초기값을 바로 nickname 을 넣거나
3-나중에 리덕스를 도입하여 처리하거나
셋 중 하나로 처리해보도록 하겠습니다...

**Comment by 42-mki** [comment]
흐음... 1, 3번을 잘 모르니 2번?!

**Comment by som-syom** [comment]
줄이는 방법을 찾았습니다

이슈 자체는 상태값인 userNickname 을 자식 컴포넌트에 props 로 넘겨주고,
자식 컴포넌트 내에선 컴포넌트 마운트가 될떄 userNickname을 쓰려고 해서 
userNickname이 초기값인 null이 들어와서 생긴 문제였습니다.
그래서 자식 컴포넌트에서 userNickname을 의존성배열(deps)에 넣고 
null 값이 아닐때만 api 요청을 보내도록 코드를 바꾸었습니다.
앞으로도 비슷한 이슈가 있을 때 참고하면 좋을거 같습니다
