### ISSUE TITLE
[2단계] 12월 13일 회의할 것

### ISSUE THREAD

**Issue by 42-mki** [42openproject/whatdidyoueat#95]
- [x] pc 화면 템플릿 : 현재 모바일뷰만 생각하고있는데 그~래도 pc 화면에서도 잘 보이게 하려고 max-width 600px을 간간히 적용중인데 한번씩 확인해서 괜찮은지 보고 적용해도 될지 이야기나누어보아요 - dhyeon
- [x] 여러 문서화가 시급해보입니당...
- [x] 2단계 에서 3단계 넘어갈때 해야할것들... (리팩토링 등...)
- [x] 2단계~3단계 사이에 필요한것이긴한데, 모든 함수에 대한 test 필요해보입니다... 어떤값이 들어와도 터지지않도록 할 필요가 있어요
- [x] 풀리퀘나 이슈에 메세지 작성 꼼꼼하게
- [x] 캘린더 api 조금 수정이 필요해보임 ( 한 주에 이전달/다음달이 겹쳐서 있는 경우 )

**Comment by som-syom** [comment]
## [필요한 문서화 리스트]
1. 멀터
2. s3
3. ERD 새로 만들기
4. 시퀄라이즈 사용법
5. 프론트엔드 배포 방법 문서화(CI CD) - 3단계 진행하면서...
6. 캘린더 만들기

## [2단계 ~ 3단계 넘어갈때 해야할것들]

- [ ] 문서화 1,2,3,4,6
- [ ] #75 
- [ ] #96 
- [ ] #104 
- [ ] 테스트코드 작성(어떤 인자가 들어와도 제어가능하도록 - 안터지도록)
- [ ] 캘린더 api 수정
- [ ] 끝나면 master에 머지
- [ ] README 수정

**Comment by som-syom** [comment]
6 문서화 개인 TIL 에 올렸는데 여기다 링크올릴게요
https://github.com/som-syom/TIL/issues/8
여기말고 wiki에도 같이 올리는게 좋겟죠..?

**Comment by 42-mki** [comment]
위키에 올려도 좋고, 안올려도 무방해 보여요

**Comment by 42-mki** [comment]
Wiki 3단계 1번째 회의에 정리했기 때문에 닫습니다.

https://github.com/42openproject/whatdidyoueat/wiki/3%EB%8B%A8%EA%B3%84-1%EB%B2%88%EC%A7%B8-%ED%9A%8C%EC%9D%98
